### ISSUE TITLE
Добавьте мод

### ISSUE THREAD

**Issue by mansur54321** [cucumber-sp/yandex-music-linux#101]
Я недавно видел что для яндекса есть модифицированный клиент, но не знаю как его добавить в arch
[YandexMusicModClient](https://github.com/TheKing-OfTime/YandexMusicModClient)

**Comment by cucumber-sp** [comment]
В таком виде нельзя интегрировать. Это как миниму должны быть патчи а не вручную поменяный сурс музыки
