### ISSUE TITLE
Управление колонкой из приложения

### ISSUE THREAD

**Issue by DFSko** [cucumber-sp/yandex-music-linux#104]
Подскажите, мобильное приложение Я.Музыка может управлять музыкой на колонке с Алисой (есть возможность запускать на колонке прейлист, волну, переключать треки)

А в это приложение эту фичу еще не завезли или оно просто не работает?

**Comment by cucumber-sp** [comment]
Это нужно в яндекс писать, в бета клиенте такого не было

**Comment by ein-shved** [comment]
Была по началу заглушка, но она пропала =(
