### ISSUE TITLE
Зависимости в archlinux

### ISSUE THREAD

**Issue by mopo3ilo** [cucumber-sp/yandex-music-linux#109]
Можно ли в PKGBUILD заменить зависимость electron29 на electron, а то уже 32 версия, а старый всё ещё не тянется. Или действительно именно 29 версия нужна для работы?

**Comment by cucumber-sp** [comment]
Когда в прошлый раз вставал об этом вопрос, был электрон 30, и он крашился на линуксе всегда, хоть и был в релизе якобы. Так что на последнюю версию опасно обновляться.

**Comment by cucumber-sp** [comment]
https://github.com/cucumber-sp/yandex-music-linux/commit/88a798d2c217f434f9f1f58be48d81af3eafdedc
