### ISSUE TITLE
Could not connect to apt.cucumber-space.online:443 (95.174.95.122), connection timed out

### ISSUE THREAD

**Issue by Egorundel** [cucumber-sp/yandex-music-linux#111]
```cmd
Err:13 https://apt.cucumber-space.online ./ InRelease                          
  Could not connect to apt.cucumber-space.online:443 (95.174.95.122), connection timed out
  ```

**Comment by verasminsk** [comment]
@cucumber-sp опять что-то случилось? :(

_Err:16 https://apt.cucumber-space.online ./ InRelease
  Could not connect to apt.cucumber-space.online:443 (95.174.95.122), connection timed out_

**Comment by cucumber-sp** [comment]
> @cucumber-sp опять что-то случилось? :(
> 
> _Err:16 https://apt.cucumber-space.online ./ InRelease Could not connect to apt.cucumber-space.online:443 (95.174.95.122), connection timed out_

Перезапустил.
