### ISSUE TITLE
Server side decorations flag

### ISSUE THREAD

**Issue by AndyDroid10X** [cucumber-sp/yandex-music-linux#119]
Good afternoon! It would be great if there was a flag or env. variable to switch to the SSD. Client decoration looks very odd and inconsistent in the DE.
![image](https://github.com/user-attachments/assets/dbceacd4-e402-4220-a5a6-983cdb33d847)

**Comment by thodt** [comment]
Было бы неплохо вернуть возможность включения системного заголовка окна.
У меня на KDE кнопки окон находятся слева, а в последнем релизе отключили системный заголовок и кнопки переехали вправо. Стало не очень удобно.

**Comment by Egorundel** [comment]
Да, жалко, что теперь стиль окна перестал зависеть от системы(

**Comment by cucumber-sp** [comment]
Теперь виндовый тайтл бар опциональный. https://github.com/cucumber-sp/yandex-music-linux/commit/32faed647c0357c9152cb03a2624143d3fe9ce75

**Comment by cucumber-sp** [comment]
Системный снова дефолтный
