### ISSUE TITLE
Window control buttons

### ISSUE THREAD

**Issue by N08I40K** [cucumber-sp/yandex-music-linux#122]
After the update (from apt), the window control buttons (minimize, maximize, close) are now displayed on the left.
![image](https://github.com/user-attachments/assets/2a6779a5-ee35-4d48-a1ab-8decfaca05dc)

Is there any way to configure the side on which they will be displayed?

Distro: Ubuntu 24.04.1 LTS
Desktop environment: GNOME 46.0
Version (apt): yandex-music/unknown,now 5.22.1 amd64

**Comment by N08I40K** [comment]
I know that you can enable a custom title bar by changing CUSTOM_TITLE_BAR in the application config, but is there an option to do without it?

**Comment by cucumber-sp** [comment]
What do you use to configure buttons position in your system? For me, button position I set with gnome-tweaks works fine with the app

**Comment by N08I40K** [comment]
I didn't change the default settings. In gnome-tweaks I have the default value, i.e. on the right.

All other applications have control buttons displayed on the right.

![image](https://github.com/user-attachments/assets/4050fa1e-798b-45a2-9410-4afc8e465dcb)

![image](https://github.com/user-attachments/assets/d96abb68-b05c-4ef3-8a77-7a960bf4eac8)

**Comment by cucumber-sp** [comment]
> I didn't change the default settings. In gnome-tweaks I have the default value, i.e. on the right.
> 
> 
> 
> All other applications have control buttons displayed on the right.
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/4050fa1e-798b-45a2-9410-4afc8e465dcb)
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/d96abb68-b05c-4ef3-8a77-7a960bf4eac8)
> 
> 
> 
> 

What if you try to set left and then back to right?

**Comment by N08I40K** [comment]
> What if you try to set left and then back to right?

After that, the buttons are displayed as they should be.
But it's still quite strange, because I've never had this in any application, and I've never changed the sides of the buttons.
