### ISSUE TITLE
README: please add: what is the difference from the website?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [cucumber-sp/yandex-music-linux#126]
I see no difference...

**Comment by N08I40K** [comment]
https://github.com/cucumber-sp/yandex-music-linux/tree/master?tab=readme-ov-file#about

This is a repack of the official Yandex Music application for Linux.

**Comment by vitaly-zdanevich** [comment]
Ok, but still visitors of your repo would like to know - that is the difference from the official application vs the website?

**Comment by N08I40K** [comment]
> that is the difference from the official application vs the website?

So why don't users go to the [official Yandex Music site](https://music.yandex.ru/download/)?
