### ISSUE TITLE
Preferences icon mistake position

### ISSUE THREAD

**Issue by denisdts** [cucumber-sp/yandex-music-linux#127]
Hello
When  resize window on Linux Zorin OS 17.3 pro
Preferences icon places  incorrect

![image](https://github.com/user-attachments/assets/84886e95-3927-42b6-8626-9eb1138ebd05)

**Comment by cucumber-sp** [comment]
Не очень понимаю в чем проблема?

**Comment by cucumber-sp** [comment]
Не занимаемся версткой, только портом оригинального приложения. А по скринам все норм, вместе с текстом песни отцентрировано

**Comment by ein-shved** [comment]
@cucumber-sp предлагаю настроить шаблон репорта ишей таким образом, чтобы он требовал от репортеров приложить поведение соответсвующей версии приложения из-под винды или мак-оси.

**Comment by cucumber-sp** [comment]
> > Не занимаемся версткой, только портом оригинального приложения. А по скринам все норм, вместе с текстом песни отцентрировано
> 
> 
> 
> Понимаю, но я про шестерёнку именно, которая гуляет.
> 
> Мелочь конечно, можно пережить.
> 
> 
> 
> @ein-shved 
> 
> По версии, я изначально писал, что линукс и какой.
> 
> да, не указал, что последняя версия самого плеера

Так она не гуляет, там неактивная кнопка текста песни, между ними гэп и они вместе отцентрированы
