### ISSUE TITLE
Unable to start playing music.

### ISSUE THREAD

**Issue by N08I40K** [cucumber-sp/yandex-music-linux#129]
After updating to version 5.25.1, my music stopped playing.

I tried reinstalling Yandex Music, but nothing changed.

If I roll back to the old version (I downloaded the [.deb package](https://github.com/cucumber-sp/yandex-music-linux/releases/tag/v5.23.2)), everything works as it should.

Here is an example:
[Screencast from 2024-10-26 19-03-27.webm](https://github.com/user-attachments/assets/eb628019-9112-42ed-9d9e-9b355372be87)

Distro: Ubuntu 24.04.1 LTS
Desktop environment: GNOME 46.0
Version (apt): yandex-music/unknown,now 5.25.1 amd64

**Comment by N08I40K** [comment]
This happens when playing any track, not only in "My Wave"

**Comment by mmagistra** [comment]
same issue on arch

**Comment by DeL00M** [comment]
I have the same problem after update to 5.25.1.

**Comment by Engen03** [comment]
Arch, Same.
Console output in the file
[yandex-music.log](https://github.com/user-attachments/files/17531834/yandex-music.log)

**Comment by mmagistra** [comment]
How can I roll back the application version and is it even possible to do this?

**Comment by DeL00M** [comment]
> How can I roll back the application version and is it even possible to do this?

Remove current version, and manually install previous one from this page

https://github.com/cucumber-sp/yandex-music-linux/releases

**Comment by mmagistra** [comment]
thx

**Comment by asaldele1** [comment]
The problem is that secretkey is empty

**Comment by ZeynX92** [comment]
Ubuntu 24.04.1 LTS same problem, so waiting approve of pull request
