### ISSUE TITLE
Не воспроизводятся треки | Arch / Hyprland

### ISSUE THREAD

**Issue by Pr0fiTX** [cucumber-sp/yandex-music-linux#138]
После нажатия на кнопку воспроизведения трека моментально останавливается (трек). Также нет кнопки "скачать". Ничего не менял в конфигах. Устанавливал с помощью yay. Запускал из консоли под обычными правами.
![241207_11h47m47s_screenshot](https://github.com/user-attachments/assets/70637d4b-9a11-473c-a704-9b3ff4d76079)
![241207_11h48m18s_screenshot](https://github.com/user-attachments/assets/ab066a89-9825-4d0c-82fd-94729d0fee7b)

**Comment by ArtKV1** [comment]
Такая же проблема на Mint
![image](https://github.com/user-attachments/assets/f6580382-0246-448f-99a1-320f29e1645f)

**Comment by Minorih06** [comment]
Тоже Mint, та же проблема
![image](https://github.com/user-attachments/assets/fb38d4f9-2fa2-48d6-80b9-3b3f73385a7d)

**Comment by ArtKV1** [comment]
Пока что решил проблему тем, что откатился на предыдущую версию (v5.29.3)

**Comment by Minorih06** [comment]
> Пока что решил проблему тем, что откатился на предыдущую версию (v5.29.3)

Это конечно выход, но не решение)

**Comment by hrueschwein** [comment]
Аналогично, openSUSE (KDE Plasma 6), Pipewire

**Comment by cucumber-sp** [comment]
Воспроизведение исправено в крайнем кооммите. Насчет скачивания, проверьте пожалуйста доступно ли в данный момент оно в Windows версии

**Comment by Vyacheslav-S** [comment]
Версия v5.32.2 не воспроизводятся треки, система Arch Linux.
v5.29.3 - проблем нет.
