### ISSUE TITLE
Music not palying

### ISSUE THREAD

**Issue by TorusHelm** [cucumber-sp/yandex-music-linux#143]
Hi, i can't play any song, but all other is ok

![image](https://github.com/user-attachments/assets/510e6e4c-4390-4b46-8c52-40dc3ff76539)

**Comment by TorusHelm** [comment]
comes with last patch v5.32.2

**Comment by verasminsk** [comment]
+1
Linux strix 6.11.0-13-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Sat Nov 30 23:51:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
![image](https://github.com/user-attachments/assets/da2d358d-9a4c-4393-873e-774dcfdfef62)

**Comment by nikonbite** [comment]
+1

**Comment by KharLexis** [comment]
+1

**Comment by GorINIch73** [comment]
+1
