### ISSUE TITLE
Switch to patching files

### ISSUE THREAD

**Issue by cucumber-sp** [cucumber-sp/yandex-music-linux#15]
Patch files instead of using sed

_Originally posted by @ein-shved in https://github.com/cucumber-sp/yandex-music-linux/issues/11#issuecomment-1919577048_

**Comment by cucumber-sp** [comment]
@ein-shved как вы предлагаете патчить файлы?

**Comment by ein-shved** [comment]
@cucumber-sp  предлагаю использовать собственно утилиту `patch`. Патчи можно генерировать гитом. Думаю процесс можно пока вручную проводить тут ничего сложного. Главное прикрутить build-валидацию, чтобы хоть частично быть уверенным, что патчи накладываются успешно при перещелкивании на новую версию.

**Comment by cucumber-sp** [comment]
> @cucumber-sp предлагаю использовать собственно утилиту `patch`. Патчи можно генерировать гитом. Думаю процесс можно пока вручную проводить тут ничего сложного. Главное прикрутить build-валидацию, чтобы хоть частично быть уверенным, что патчи накладываются успешно при перещелкивании на новую версию.

хм, а как должна build валидация работать? Сейчас я все пакеты собираю на локальной машине. Хотите это в облако перенести?

**Comment by ein-shved** [comment]
Есть github actions. Не пользовался, и не знаю, как это работает, но вроде это как раз таки местный CI. По крайней мере на него ссылается [cachix](https://docs.cachix.org/continuous-integration-setup/)

**Comment by cucumber-sp** [comment]
> Есть github actions. Не пользовался, и не знаю, как это работает, но вроде это как раз таки местный CI. По крайней мере на него ссылается [cachix](https://docs.cachix.org/continuous-integration-setup/)

да, самый популярный вариант, если бесплатного тарифа хватит то можно использовать. но это уже к другому issue относится. по поводу патчинга файлов - нужно занятся. sed для фикса secretKey продолжу использовать т.к. там каждый раз меняется файлы, а вот для основных хендлеров и тд можно использовать патчинг я думаю без проблем

**Comment by cucumber-sp** [comment]
https://github.com/cucumber-sp/yandex-music-linux/commit/13a6e87a40d934127c7d24f8aefdb570c26820d5
