### ISSUE TITLE
Change naming in Nix

### ISSUE THREAD

**Issue by ein-shved** [cucumber-sp/yandex-music-linux#16]
How does the `yandex`?`music.exe` named in windows? We have two styles of naming here:
* `yandex-music` in nix-related files. Chosen according to nix-way
* `yandexmusic` in other places here.

Let's agree here on correct naming.

- [ ] Rename `yandex-music` to `yandexmusic` in nix files @ein-shved

**Comment by cucumber-sp** [comment]
yandexmusic предпочтительный в большинстве дистрибутивов, использую для deb и arch сейчас.

**Comment by ein-shved** [comment]
Это ваше решение, или разработчиков Я.Музыки?

**Comment by cucumber-sp** [comment]
> Это ваше решение, или разработчиков Я.Музыки?

Моё решение) В винде вообще YandexMusic.exe

**Comment by ein-shved** [comment]
Ну 
* во-первых в винде нейминг выглядит лучше. Это конечно вусовщина, но подкрепленная тем, что имя `yandexmusic` не соответствует ни одному из широко распространенных coding-syles 
* во-вторых если вы используете другой нейминг, то вы автоматически на сможете обеспечить один нейминг во всех дистрибутивах, т.к. на Винду повлиять не сможете

так что предлагаю синхронизировать нейминг с апстримом.

**Comment by cucumber-sp** [comment]
> Ну
> 
> * во-первых в винде нейминг выглядит лучше. Это конечно вусовщина, но подкрепленная тем, что имя `yandexmusic` не соответствует ни одному из широко распространенных coding-syles
> * во-вторых если вы используете другой нейминг, то вы автоматически на сможете обеспечить один нейминг во всех дистрибутивах, т.к. на Винду повлиять не сможете
> 
> так что предлагаю синхронизировать нейминг с апстримом.

вообще стандартная практика по крайней мере для пакетов в AUR. Но если хотите переименовать в `yandex-music` и займетесь этим то я не против, но нужно сделать это везде

**Comment by ein-shved** [comment]
Не, я бы не стал переименовывать в `yandex-music`  я бы переименовал в `YandexMusix`, как это сделано в апстриме.

**Comment by cucumber-sp** [comment]
> Не, я бы не стал переименовывать в `yandex-music` я бы переименовал в `YandexMusix`, как это сделано в апстриме.

ну это уже неприемлемый нейминг для AUR пакетов да и для deb наверное тоже. Не вижу причин не оставить yandexmusic

**Comment by ein-shved** [comment]
@cucumber-sp хозяин-барин, на том и порешим. На днях докину патч в nix

**Comment by cucumber-sp** [comment]
> @cucumber-sp хозяин-барин, на том и порешим. На днях докину патч в nix

👌

**Comment by ein-shved** [comment]
Done with #19.
