### ISSUE TITLE
Arch support

### ISSUE THREAD

**Issue by cucumber-sp** [cucumber-sp/yandex-music-linux#2]
We need to add proper Arch support. Currently I just use debtap with .dep package but it doesn't sound well.

- [x] Build proper Arch packages
- [ ] Submit to AUR as `yandexmusic-bin`

**Comment by DFSko** [comment]
awaiting in AUR

**Comment by mopo3ilo** [comment]
@cucumber-sp может лучше переименовать пакет в `yandex-music` или `yandex-music-beta`, чтобы имя соответствовало другим (относительно) официальным пакетам и не резало глаза?

Официалы, полагаю, не раздуплятся ещё лет 10, так что этот пакет вполне достоен занять корректное имя :)

**Comment by cucumber-sp** [comment]
> @cucumber-sp может лучше переименовать пакет в `yandex-music` или `yandex-music-beta`, чтобы имя соответствовало другим (относительно) официальным пакетам и не резало глаза?
> 
> Официалы, полагаю, не раздуплятся ещё лет 10, так что этот пакет вполне достоен занять корректное имя :)

переименовал в yandex-music

**Comment by ein-shved** [comment]
Может тогда все вхождения `yandezmusic` переименовать в `yandex-music` обратно?)) Для единообразия)

**Comment by mopo3ilo** [comment]
@ein-shved, в pkgbuild всё так и сделано, или ты о чём?

**Comment by cucumber-sp** [comment]
> Может тогда все вхождения `yandexmusic` переименовать в `yandex-music` обратно?)) Для единообразия)

какие именно? вроде бы все переименовал

**Comment by mopo3ilo** [comment]
Я только в патчах нашёл, но не нашёл, чтобы они где-то использовались

**Comment by ein-shved** [comment]
@mopo3ilo @ein-shved Я говорю о всем проекте в целом, не только PKBUILD. Например, в nix стиль с '-' тоже предпочтительны.

**Comment by mopo3ilo** [comment]
@ein-shved, он везде понял и в никсах и в дебах, всё норм

**Comment by ein-shved** [comment]
Ааа, посмотрел патч и понял, что он понял =)))
