### ISSUE TITLE
Преобразование через alien deb пакетов не работает (спецсимвол '$'\r'')

### ISSUE THREAD

**Issue by Maks1mS** [cucumber-sp/yandex-music-linux#20]
Deb пакеты версии 5.0.8 (из Github Releases) не могу преобразовать c помощью утилиты alien в RPM на ALT Linux.
На Fedora они преобразуются, но в названии содержится спецсимвол '$'\r'', который выглядит как перенос строки.
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/36362599/272721b6-b9ad-4693-96d6-11c0de318f5a)
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/36362599/6d8825c5-f1ef-469b-8efe-e74f1b062c12)
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/36362599/9b0ae8db-b1ec-4839-9be4-7b80c129fa77)

Собранный самостоятельно в виртуальной машине ubuntu 22.04 deb пакет нормально конвертируется.

Возможно всё можно решить переносом создания релизов через CI.

**Comment by cucumber-sp** [comment]
Причина в том, что я собираю все в WSL, соответственно какие-то файлы могут иметь dos формат переносов строк. Решить можно или конвертацией всех файлов с помощью dos2unix перед сборкой, или собирать на чисто линуксовой системе (через CI подходит)

**Comment by Maks1mS** [comment]
Решено с добавлением CI
