### ISSUE TITLE
Fix CI building

### ISSUE THREAD

**Issue by cucumber-sp** [cucumber-sp/yandex-music-linux#22]

**Comment by cucumber-sp** [comment]
@Maks1mS https://github.com/cucumber-sp/yandex-music-linux/blob/2a6702b05e17daee47712e8f58cf9155a59675e5/.github/workflows/build.sh#L17
устанавливаем два раза уже jq но не помогает) видимо в чем-то другом проблема

**Comment by cucumber-sp** [comment]
@Maks1mS я бы перенес сборку deb да и rpm в будущем в арч тоже, нет особо смысла от нескольких контейнеров мне кажется, можно в одном все собрать, для deb пакетов только понадобится dpkg установить через pacman и все

**Comment by Maks1mS** [comment]
> @Maks1mS я бы перенес сборку deb да и rpm в будущем в арч тоже, нет особо смысла от нескольких контейнеров мне кажется, можно в одном все собрать, для deb пакетов только понадобится dpkg установить через pacman и все

Да, можно сделать так

**Comment by Maks1mS** [comment]
Похоже, этим комитом всё исправлено cd5016dc013495a19e4ac1fa4d7ffd99972f6e37.
Еще можно сделать релиз на [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) или [on push tags](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs).

Можно добавить что-то вроде [этого](https://github.com/python-LimeReport/python-LimeReport/blob/7e0559efcb9330cd987e6676c6d5650ec76ae41a/.github/workflows/wheels.yml#L77-L99).

**Comment by cucumber-sp** [comment]
@Maks1mS да, я бы просто заменял файлы в релизе для текущей версии новыми. То есть пока 5.0.8 то в релизе 5.0.8 заменял существующие новыми. Если сможете реализовать то будет отлично

**Comment by Maks1mS** [comment]
@cucumber-sp 

https://github.com/cucumber-sp/yandex-music-linux/blob/42c3cf52a33ed2bb914b02873e363865ab92573f/.github/workflows/update_packages.yml#L10

А должно быть

```
runs-on: ubuntu-latest
container: 
  image: archlinux:latest 
```

**Comment by cucumber-sp** [comment]
@Maks1mS вроде бы все сделали, единственное о чем вас могу попросить это добавить следующий функционал. Перед сборкой коммита проверять не обновилось ли exe яндекс музыки. Если обновилось то прекращать текущий workflow, вызвать Update Packages и он уже создав коммит с обновлениями пакетов автоматически триггернет еще одну сборку но уже с новыми пакетами. Ну и из самой сборки можно убрать обновление пакетов через generate_packages.sh

**Comment by Maks1mS** [comment]
Могу сделать, только в настройках нужно будет установить токен
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow

Как раз из-за этого и не сработало:

![image](https://github.com/cucumber-sp/yandex-music-linux/assets/36362599/c63f462d-08c7-40ac-bf81-6e619eff050c)

**Comment by cucumber-sp** [comment]
> Могу сделать, только в настройках нужно будет установить токен https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
> 
> Как раз из-за этого и не сработало:
> 
> ![image](https://private-user-images.githubusercontent.com/36362599/301918937-c63f462d-08c7-40ac-bf81-6e619eff050c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTQzNTksIm5iZiI6MTcwNjg5NDA1OSwicGF0aCI6Ii8zNjM2MjU5OS8zMDE5MTg5MzctYzYzZjQ2MmQtMDhjNy00MGFjLWJmODEtNmU2MTllZmYwNTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE3MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmM2VhZWFhYTNiMDUzZGQ1MDllMTQyODMwYWU2YTI2NDBiMmNmZjc3OTJiOWI2NjdmYWJlYWJiNDVhYmYwYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oYhktaMfWgAzPiNVBj3kEE9-bbRkg_UNesw_NAwIc3s)

а если вручную вызвать то должно сработать? С токенами возиться мне кажется целая история просто

**Comment by cucumber-sp** [comment]
> Вручную пушить комит с "Update packages to Beta", а не вызывать через `workflow_dispatch`

я имею ввиду коммит делать через action а потом из этого же action вызвать другой workflow вручную если он не триггерится с коммита

**Comment by Maks1mS** [comment]
> > Вручную пушить комит с "Update packages to Beta", а не вызывать через `workflow_dispatch`
> 
> я имею ввиду коммит делать через action а потом из этого же action вызвать другой workflow вручную если он не триггерится с коммита

Я понял, так тоже можно. Завтра займусь этим

**Comment by dikey0ficial** [comment]
Прошу прощения что, возможно, не в тему — а куда делась сборка RPM?) Сейчас на выходе только .deb, nix flake и PKGBUILD

**Comment by cucumber-sp** [comment]
> Прошу прощения что, возможно, не в тему — а куда делась сборка RPM?) Сейчас на выходе только .deb, nix flake и PKGBUILD

отказались от electron forge чтобы вручную все собирать, откройте новый issue, в течение пары дней посмотрю структуру пакетов и добавлю сборку
