### ISSUE TITLE
Ресайз окна

### ISSUE THREAD

**Issue by uvlad7** [cucumber-sp/yandex-music-linux#23]
Столкнулся с проблемой, которую и раньше встречал в электрон приложениях: нет кнопки maximize и не работает ресайз по вертикали:
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/47718845/edbc3696-f57b-4acc-9156-47d90cdf547d)
Нашёл [такой](https://stackoverflow.com/a/74570316/13500870) совет: убрать  `minWidth` и `minHeight`.
Распаковал `/usr/lib/yandexmusic/yandexmusic.asar`:
```bash
npx @electron/asar extract /usr/lib/yandexmusic/yandexmusic.asar yandexmusic
```
В директории `yandexmusic` такой патч делаем:
```diff
diff --git a/main/lib/createWindow.js b/main/lib/createWindow.js
index 771e24c..e3794a7 100644
--- a/main/lib/createWindow.js
+++ b/main/lib/createWindow.js
@@ -16,8 +16,6 @@ const createWindow = async () => {
             x: 16,
             y: 10
         },
-        minWidth: 1024,
-        minHeight: 800,
         width: 1280,
         height: 800,
         webPreferences: {
```
Собираем:
```bash
npx @electron/asar pack yandexmusic yandexmusic.asar
```
Работает:
```bash
/usr/lib/yandexmusic/electron/electron yandexmusic.asar
```
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/47718845/5525c46b-396e-497f-bc46-dba9e43ee79c)

Возможно можно починить как-то проще, конечно.

**Comment by uvlad7** [comment]
А приложение конечно довольно бессмысленное (пока), [неофициальный клиент](https://github.com/Rirusha/Cassette) лучше по функционалу и удобнее, тут например кеширования нет. Это получается не то, что в [Windows Store](https://apps.microsoft.com/detail/9NBLGGH0CB6D?hl=ru-ru&gl=RU)?

**Comment by nixway** [comment]
@uvlad7 я использую [yaamp](https://github.com/umnik1/yaamp) в репаке не работает без подписки.

**Comment by cucumber-sp** [comment]
> А приложение конечно довольно бессмысленное (пока), [неофициальный клиент](https://github.com/Rirusha/Cassette) лучше по функционалу и удобнее, тут например кеширования нет. Это получается не то, что в [Microsoft Store](https://apps.microsoft.com/detail/9NBLGGH0CB6D?hl=ru-ru&gl=RU)?

это новое официальное приложение, то что в Microsoft Store это WPF приложение, его не портировать, не нравится не используйте)

**Comment by uvlad7** [comment]
> не нравится не используйте

Это же не претензия к вам, просто удивляюсь, что яндекс вместо одного недоделанного приложения сделали ещё более недоделанное.

**Comment by cucumber-sp** [comment]
> > не нравится не используйте
> 
> Это же не претензия к вам, просто удивляюсь, что яндекс вместо одного недоделанного приложения сделали ещё более недоделанное.

ну поэтому это бета, с каждым обновлением расширяют функционал ближе к полному клиенту. когда-нибудь будет все что нужно
