### ISSUE TITLE
Сборка RPM

### ISSUE THREAD

**Issue by dikey0ficial** [cucumber-sp/yandex-music-linux#26]
Сабж

**Comment by dikey0ficial** [comment]
Всё ещё ждём, ибо новые версии приходится собирать старым скриптом)

**Comment by cucumber-sp** [comment]
> Всё ещё ждём, ибо новые версии приходится собирать старым скриптом)

а alien разве не работает? ну можете сами сделать сборку rpm по аналогии с deb, я сейчас просто не знаю когда у меня найдется время на это

**Comment by dikey0ficial** [comment]
> а alien разве не работает?

У меня при перепаковке последней версии в .deb такое вылезает:
```
(node:18550) UnhandledPromiseRejectionWarning: Error: Failed to load image from path 'build/next-desktop/favicon.png'
    at createTray (/usr/lib/yandexmusic/yandexmusic.asar/main/lib/createTray.js:4:16)
    at /usr/lib/yandexmusic/yandexmusic.asar/main/index.js:34:5
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:18550) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
При попытках запустить с `--unhandled-rejections=none` тоже не идёт)

**Comment by cucumber-sp** [comment]
> > а alien разве не работает?
> 
> У меня при перепаковке последней версии в .deb такое вылезает:
> 
> ```
> (node:18550) UnhandledPromiseRejectionWarning: Error: Failed to load image from path 'build/next-desktop/favicon.png'
>     at createTray (/usr/lib/yandexmusic/yandexmusic.asar/main/lib/createTray.js:4:16)
>     at /usr/lib/yandexmusic/yandexmusic.asar/main/index.js:34:5
> (Use `electron --trace-warnings ...` to show where the warning was created)
> (node:18550) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> ```
> 
> При попытках запустить с `--unhandled-rejections=none` тоже не идёт)

да, это общая проблема после того как добавил tray, сейчас буду исправлять

**Comment by cucumber-sp** [comment]
@dikey0ficial исправлено с https://github.com/cucumber-sp/yandex-music-linux/commit/3eb7fe7816733cf8a62d139d55e57cfe659fbc7a как соберуться новые файлы можете попробовать alien

**Comment by dvapack** [comment]
привет, последние версии не получается поставить через alien, можешь пожалуйста добавить rpm?

**Comment by cucumber-sp** [comment]
> привет, последние версии не получается поставить через alien, можешь пожалуйста добавить rpm?

сейчас нет времени этим заняться, если кто-то сделает скрипт по аналогии с deb для сборки то тогда конечно добавлю

**Comment by cucumber-sp** [comment]
@dvapack попробовал сделать. Скачайте файл из релизов, проверьте работает ли.

**Comment by dvapack** [comment]
Error running transaction: file /usr/bin from install of yandex-music-5.0.14-1.x86_64 conflicts with file from package filesystem-3.18-6.fc39.x86_64
file /usr/lib from install of yandex-music-5.0.14-1.x86_64 conflicts with file from package filesystem-3.18-6.fc39.x86_64

**Comment by cucumber-sp** [comment]
> Error running transaction: file /usr/bin from install of yandex-music-5.0.14-1.x86_64 conflicts with file from package filesystem-3.18-6.fc39.x86_64 file /usr/lib from install of yandex-music-5.0.14-1.x86_64 conflicts with file from package filesystem-3.18-6.fc39.x86_64

попробуйте ещё раз с новым

**Comment by dvapack** [comment]
получилось, всё работает, спасибо огромное!)
