### ISSUE TITLE
Cachix workflow does not works as expected

### ISSUE THREAD

**Issue by ein-shved** [cucumber-sp/yandex-music-linux#31]
Настроенный по [инструкции](https://nix.dev/tutorials/nixos/continuous-integration-github-actions) workflow выплевывает ошибку
```
 Pushing is disabled as signingKey nor authToken are set (or are empty?) in your YAML file.
```

**Comment by cucumber-sp** [comment]
> Настроенный по [инструкции}(https://nix.dev/tutorials/nixos/continuous-integration-github-actions) workflow выплевывает ошибку
> 
> ```
>  Pushing is disabled as signingKey nor authToken are set (or are empty?) in your YAML file.
> ```

где именно эта ошибка?

**Comment by ein-shved** [comment]
`build/nix-build` -> `Post Run cachix/cachix-action@v12` -> `Cachix: push`

**Comment by cucumber-sp** [comment]
исправил в https://github.com/cucumber-sp/yandex-music-linux/commit/c232e2b543eb359868d8cab289281a0cf6ca3cba

**Comment by ein-shved** [comment]
@cucumber-sp хмм  я вижу такое же сообщение на этот коммит...

**Comment by cucumber-sp** [comment]
> @cucumber-sp хмм я вижу такое же сообщение на этот коммит...

да, увидел

**Comment by cucumber-sp** [comment]
https://github.com/cucumber-sp/yandex-music-linux/commit/b2f350b8490d972ad7cfd7984c9ee6ff8e232761

**Comment by ein-shved** [comment]
К сожалению, такой вариант в принципе отключает публикацию артефактов. Если такой вариант устраивает, то ок.
