### ISSUE TITLE
Window bar title icon broken for Xfce or NixOS

### ISSUE THREAD

**Issue by ein-shved** [cucumber-sp/yandex-music-linux#32]
У меня под NixOs и Xfce проявляется такой вот баг
![Icon bug](https://github.com/cucumber-sp/yandex-music-linux/assets/3513222/f0290bd7-15f3-4c68-9f82-58a8301c5cce)
Пока не понятно кто виноват - Xfce или NixOS. Если ни у кого не установлен Xfce, попробую найти время чтобы запустить на xubuntu в qemu.

**Comment by cucumber-sp** [comment]
![изображение](https://github.com/cucumber-sp/yandex-music-linux/assets/100789522/e136bdb4-4604-416f-bb9f-562c6ee92fe5)
у меня на Xfce вот так, но это тоже арч

**Comment by dibusure** [comment]
А ты сам собирал или уже опакетили?
