### ISSUE TITLE
Нужна опция, что хотим получить на выходе

### ISSUE THREAD

**Issue by x09** [cucumber-sp/yandex-music-linux#35]
Чтобы можно было задать zip, rpm или deb.
Что-то одно.

**Comment by cucumber-sp** [comment]
> Чтобы можно было задать zip, rpm или deb. Что-то одно.

не понимаю, и так для разных форматов разные скрипты сбррки

**Comment by x09** [comment]
> > Чтобы можно было задать zip, rpm или deb. Что-то одно.
> 
> не понимаю, и так для разных форматов разные скрипты сбррки

repack -t zip Yandex.exe

на выходе только zip

**Comment by cucumber-sp** [comment]
> > > Чтобы можно было задать zip, rpm или deb. Что-то одно.
> > 
> > 
> > не понимаю, и так для разных форматов разные скрипты сбррки
> 
> repack -t zip Yandex.exe
> 
> на выходе только zip

зачем? и так на выходе только asar или распакованный проект. Для каждой платформы есть свой скрипты сборки, читайте Readme

**Comment by x09** [comment]
> > > > Чтобы можно было задать zip, rpm или deb. Что-то одно.
> > > 
> > > 
> > > не понимаю, и так для разных форматов разные скрипты сбррки
> > 
> > 
> > repack -t zip Yandex.exe
> > на выходе только zip
> 
> зачем? и так на выходе только asar или распакованный проект. Для каждой платформы есть свой скрипты сборки, читайте Readme

затем, что , к примеру, на Альте пытается делать все сразу и не делает в итоге ничего (вываливается с грудой ошибок что rpm не той версии, хотя он той). но хоть в out есть распакованые файлы.

**Comment by cucumber-sp** [comment]
> > > > > Чтобы можно было задать zip, rpm или deb. Что-то одно.
> > > > 
> > > > 
> > > > не понимаю, и так для разных форматов разные скрипты сбррки
> > > 
> > > 
> > > repack -t zip Yandex.exe
> > > на выходе только zip
> > 
> > 
> > зачем? и так на выходе только asar или распакованный проект. Для каждой платформы есть свой скрипты сборки, читайте Readme
> 
> затем, что , к примеру, на Альте пытается делать все сразу и не делает в итоге ничего (вываливается с грудой ошибок что rpm не той версии, хотя он той). но хоть в out есть распакованые файлы.

сейчас нет сборки для rpm, используйте alien с deb пакетами. я думаю вы используете очень старую версию скрипта, склонируйте репозиторий или обновите, все сейчас по другому работает

**Comment by x09** [comment]
Да, версия была не последней.
Но сейчас совсем неудобно стало) repack по сути делает только asar файл.. что это и зачем мне не понятно..
build_deb, да колхозит deb, но когда хочешь колбасы, а тебе говорят вот поешь холодца - так себе выбор)

Я к чему все это. Я для себя, и таких как я, собираю rpm, для Альта в свой репо.
Сам пишу spec, делаю дополнительные телодвижения, ярлычок там, иконки, нужные моменты для sysctl и собираю. Было бы удобно на входе, в качестве sources - иметь tgz/zip/7z/...  До сих пор просто брал руками папку out, заворачивал в архив дальше все само по спеку, на выходе правильный  rpm.
Ну ок, можно и deb брать как source, распаковывать его и собирать в rpm.. но лишние шаги.

**Comment by cucumber-sp** [comment]
@x09 так вам и нужен этот asar файл, далее скачиваете бинарник electron, и через него запускаете asar файл. У нас есть issue по поддержке rpm. если сможете сделать скрипт для сборки пакетов вам будут благодарны. у меня пока на это времени не было просто. repack именно перепаковывает ресурсы приложения, а сборка уже происходит нативными средствами платформы. PKGBUILD на арче, на nix тоже свои файлы.

**Comment by x09** [comment]
Хорошо, посмотрю чем помочь.

**Comment by cucumber-sp** [comment]
> Хорошо, посмотрю чем помочь.

может посмотреть скрипт сборки deb, как я понимаю в rpm похожая структура, нужно только другие файлы с информацией добавить
