### ISSUE TITLE
Установка из AUR падает: нет зависимости asar

### ISSUE THREAD

**Issue by TitaniumHocker** [cucumber-sp/yandex-music-linux#36]
На этапе сборки пакета из AUR происходит ошибка из-за отсутствия команды: `asar`

**Comment by cucumber-sp** [comment]
> На этапе сборки пакета из AUR происходит ошибка из-за отсутствия команды: `asar`

есть ли перед этим какие-то ошибки? мы устанавливаем asar в prepare и на моих машинах все собирается

**Comment by cucumber-sp** [comment]
Исправлено в https://github.com/cucumber-sp/yandex-music-linux/commit/7457b0065125b2f0cff4a58fac2b24f30fec7349

**Comment by cucumber-sp** [comment]
@TitaniumHocker очистите кэш сборки с помощь yay -Sc и затем запустите установку еще раз

**Comment by TitaniumHocker** [comment]
> Исправлено в [7457b00](https://github.com/cucumber-sp/yandex-music-linux/commit/7457b0065125b2f0cff4a58fac2b24f30fec7349)

А почему просто не добавить пакет `asar` в зависимости? Я его ручками поставил, чтоб фикса не ждать и все отработало.
