### ISSUE TITLE
Fix release notes

### ISSUE THREAD

**Issue by cucumber-sp** [cucumber-sp/yandex-music-linux#40]
@ein-shved если есть возможность, посмотрите пожалуйста что там за проблема с получением строки из файла, т.к. у меня в ближайшее время доступа к десктопу не будет

**Comment by ein-shved** [comment]
@cucumber-sp у меня, боюсь, до воскресенья - тоже(

**Comment by cucumber-sp** [comment]
> @cucumber-sp у меня, боюсь, до воскресенья - тоже(

понял, тогда не беспокою)
