### ISSUE TITLE
Broken icon

### ISSUE THREAD

**Issue by DFSko** [cucumber-sp/yandex-music-linux#46]
After updating AUR package from yandexmusic to yandex-music icon in gnome dock is broken
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/811811/9f7f32d8-c6a8-49c6-a6a8-640ec28d4863)

**Comment by cucumber-sp** [comment]
@DFSko try
```
yay -R yandexmusic
yay -R yandex-music
yay -Sc
yay -S yandex-music
```
to build it without cache or anything else

**Comment by DFSko** [comment]
Tried, but unfortunately it didn't help

**Comment by DFSko** [comment]
How to fix:

1. Press Alt+F2 and type lg
In opened window press "Windows" button
As you can see yandex-music app has "YandexMusic" wmclass
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/811811/0310cd73-4cc8-4e56-a897-ba695498b2c8)


2. Copy yandex-music.desktop file from /usr/share/applications to ~/.local/share/applications
3. Edit yandex-music.desktop file. Add line
``` StartupWMClass=YandexMusic ``` 

For app is tracked and icon works
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/811811/ea2a6f92-d54f-4e4a-9086-93331a39fd25)

**Comment by cucumber-sp** [comment]
Fixed with https://github.com/cucumber-sp/yandex-music-linux/commit/f6788ec30a3c87d0b74e21339a4e3568aed2be57
