### ISSUE TITLE
Tree menu i18n

### ISSUE THREAD

**Issue by DFSko** [cucumber-sp/yandex-music-linux#47]
Please add i18n support to tree menu
In system with russian localization tree menu in english
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/811811/702630ea-13a9-478d-bd24-f80dd971fd26)

**Comment by Maks1mS** [comment]
Предлагаю просто заменить эти надписи на русские, т.к. само приложение поддерживает только русский.

**Comment by cucumber-sp** [comment]
> Предлагаю просто заменить эти надписи на русские, т.к. само приложение поддерживает только русский.

Согласен, сделаю
