### ISSUE TITLE
Yandex music icons

### ISSUE THREAD

**Issue by nixway** [cucumber-sp/yandex-music-linux#5]
I extracted the icons from the original Windows client. I attach an archive with the directory structure preserved for the Linux client.
[yandexmusic.5.0.5.x64.zip](https://github.com/cucumber-sp/yandex-music-linux/files/14000230/yandexmusic.5.0.5.x64.zip)

P. S. A little tweak to the yandexmusic.desktop file:
```
[Desktop Entry]
Version=1.0
Name=Yandex Music
Name[ru]=Яндекс Музыка
Comment=Music streaming service
Comment[ru]=Музыкальный стриминговый сервис
Exec=yandexmusic %U
Icon=yandexmusic
Type=Application
Terminal=false
StartupNotify=true
Categories=AudioVideo;
```

**Comment by cucumber-sp** [comment]
Do you know how we can integrate injecting icons into building process?

**Comment by ein-shved** [comment]
Btw. All this done for Nix. You do not need to extract the Icons, they are already in package, taken [here](https://github.com/cucumber-sp/yandex-music-linux/blob/main/nix/default.nix#L37) by nix.

**Comment by nixway** [comment]
Great job! Aren't there any icons in png format in one of the sizes {16,22,24,32,32,48,48,64,64,96,96,128,256,512}? On the other hand, the icon is simple and would look decent when scaled.

**Comment by ein-shved** [comment]
There is vector icon. As I understand, you do not need to scale it by hand.
