### ISSUE TITLE
There is no transparency in the tray icon

### ISSUE THREAD

**Issue by sjschukin** [cucumber-sp/yandex-music-linux#52]
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/2988026/6760ce5c-aba2-4510-9ddd-a95331e1806b)
Сейчас значок выглядит вот так. Аналогично и у самого приложения в панели запуска.
Linux Mint 21.3 Cinnamoon

**Comment by ein-shved** [comment]
А как он на винде выглядит?

**Comment by cucumber-sp** [comment]
![Screenshot_20240221-074347](https://github.com/cucumber-sp/yandex-music-linux/assets/100789522/b20b22d9-b7f5-4c60-b7d3-ef38417f9709)
а как должно быть?

**Comment by DFSko** [comment]
закругленный может? и хотелось бы монохромный в трей

**Comment by ein-shved** [comment]
Мне кажется, подобные запросы нужно отправлять разработчикам в Я, либо предлагать патчи самостоятельно.

**Comment by cucumber-sp** [comment]
> закругленный может? и хотелось бы монохромный в трей

мы используем те же что и в приложении, можете сделать pull request с монохромными иконками, но я не очень представляю как это правильно сделать, разве что добавлять в locolor пак
