### ISSUE TITLE
possible issue on latest ubuntu

### ISSUE THREAD

**Issue by netwarebsd** [cucumber-sp/yandex-music-linux#59]
Использую Ubuntu 24.04 (пред-релизная)
Приложение ставится но не запускается, пробовал версии 5.0.11 и 5.0.12 результат неизменен, может кто вкурсе может по умолчанию в системе нет чего-то? Надо что-то доставить или где-то лог можно посмотреть?

Ошибки никакой не возникает просто не запускается

**Comment by cucumber-sp** [comment]
А если через консоль `yandex-music'?

**Comment by netwarebsd** [comment]
> А если через консоль `yandex-music'?

$ yandex-music
[10437:0301/123855.716704:FATAL:credentials.cc(127)] Check failed: . : Отказано в доступе (13)
Ловушка трассировки/останова (образ памяти сброшен на диск)

**Comment by cucumber-sp** [comment]
попробуйте `yandex-music --no-sandbox`

**Comment by netwarebsd** [comment]
> yandex-music --no-sandbox

Благодарю - заработало!

**Comment by ein-shved** [comment]
@cucumber-sp, мне кажется, не стоит ее просто закрывать, а что-то делать, с тем, чтобы не нужно было всегда запускать с флагом на убунте 24.04

**Comment by cucumber-sp** [comment]
> @cucumber-sp, мне кажется, не стоит ее просто закрывать, а что-то делать, с тем, чтобы не нужно было всегда запускать с флагом на убунте 24.04

я ещё проверю, но у меня всё на убунте было ок, вероятно какая-то локальная проблема, если поискать то с electron такое бывает

**Comment by ein-shved** [comment]
@cucumber-sp  у тебя тоже 24.04?

**Comment by ein-shved** [comment]
Может быть проблема в версии electron? @netwarebsd какая версия electron стоит?

**Comment by cucumber-sp** [comment]
> Может быть проблема в версии electron? @netwarebsd какая версия electron стоит?

на deb электрон включен в пакет

**Comment by ein-shved** [comment]
> электрон включен в пакет

О_о он прям в пакет запихивается, не как зависимость притягивается?

**Comment by cucumber-sp** [comment]
> > электрон включен в пакет
> 
> О_о он прям в пакет запихивается, не как зависимость притягивается?

да, не существует такой зависимости просто, поэтому по гайдлайнам включаем в пакет бинарник

**Comment by ein-shved** [comment]
Ужос

**Comment by netwarebsd** [comment]
> > Может быть проблема в версии electron? @netwarebsd какая версия electron стоит?
> 
> на deb электрон включен в пакет



> Может быть проблема в версии electron? @netwarebsd какая версия electron стоит?

Никакая не стоит сообщает мне система, но ставил как ра деб пакет

**Comment by cucumber-sp** [comment]
fixed with https://github.com/cucumber-sp/yandex-music-linux/commit/d41280817c68807bad5d0f52ec95535170a8c6dd

**Comment by cucumber-sp** [comment]
> Обновил версию запускается сразу и без проблем

да, выше упомянул коммит в котором добавил фикс
