### ISSUE TITLE
Fix NIX Build

### ISSUE THREAD

**Issue by cucumber-sp** [cucumber-sp/yandex-music-linux#61]

**Comment by cucumber-sp** [comment]
@ein-shved можете проверить в чем ошибка со сборкой Nix и исправить?

**Comment by ein-shved** [comment]
Завтра гляну

**Comment by ein-shved** [comment]
@cucumber-sp а не подскажешь, зачем в принципе ты завел проверку на CI, раз заливаешь патчи в мастер, не проверяя их. Проблема в комите 8bf1352 и на CI она проявилась.

**Comment by cucumber-sp** [comment]
> @cucumber-sp а не подскажешь, зачем в принципе ты завел проверку на CI, раз заливаешь патчи в мастер, не проверяя их. Проблема в комите [8bf1352](https://github.com/cucumber-sp/yandex-music-linux/commit/8bf13524b58bef8a34832452cadd3c5a954a2182) и на CI она проявилась.

не проверка на CI, а сборка. Проверка идёт только на пулл реквест.

**Comment by ein-shved** [comment]
Так в том то и вопрос, почему ты не проверяешь свои коммиты?

**Comment by cucumber-sp** [comment]
> Так в том то и вопрос, почему ты не проверяешь свои коммиты?

хорошо, буду на dev делать)

**Comment by ein-shved** [comment]
Я бы предложил настроить запрет на push в master

**Comment by cucumber-sp** [comment]
> Я бы предложил настроить запрет на push в master

да, можно сделать, сейчас гляну
