### ISSUE TITLE
Управление через иконку в трее.

### ISSUE THREAD

**Issue by mcdemon05** [cucumber-sp/yandex-music-linux#67]
Добрый день.
Для себя осознал, что музыка через Яндекс.Браузер получается удобнее за счет того, что паузу например можно поставить в боковом меню браузера, даже если ты не находишься во вкладке музыки.
А когда музыка в отдельном приложении, то для паузы нужно раскрывать само приложение, то-есть больше телодвижений....
Как вариант в голову приходит, чтобы можно было по иконке в трее нажать ПКМ и появится пункт в выпадающем меню с pause/play

**Comment by ein-shved** [comment]
Я настроил десктопный хоткей на `playerctl play-pause` все работает четко, и не нужен никакой трей.

**Comment by mcdemon05** [comment]
Это наверное клавиатурный хоткей.
Уверен, что это тоже полезно.
Но иногда хочется сделать это именно мышкой.

**Comment by ein-shved** [comment]
Возможно. Ждем в таком случае PR =)

**Comment by cucumber-sp** [comment]
у меня в гноме в центральном меню сверху (при клике на дату) и так появляется плеер где можно переключать все. А что за десктоп у вас?

**Comment by ein-shved** [comment]
Кстати да, в xfce для этого есть PulseAudio applet 
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/3513222/f69a1e25-7f54-46e5-ac7f-533aca014496)

**Comment by mcdemon05** [comment]
Fedora 39
GNOME

Действительно, если нажать на часы то откроется менюшка с уведомлениями и там я могу нажать на паузу.
Спасибо.
