### ISSUE TITLE
Низкое качество обложек в MPRIS

### ISSUE THREAD

**Issue by PoSayDone** [cucumber-sp/yandex-music-linux#70]
В MPRIS приходят обложки в разрешении 150x150, реально ли будет сделать так, чтобы они были в высоком разрешении?
![aa45ad2a77f027bba003185fe85da6594dabd68a](https://github.com/cucumber-sp/yandex-music-linux/assets/29358657/fa5b6a78-2be8-452f-9712-5439577d6df4)

**Comment by ein-shved** [comment]
Мне кажется, это вопрос к разработчикам из Я.
