### ISSUE TITLE
Пропал значок в трее

### ISSUE THREAD

**Issue by mishich666** [cucumber-sp/yandex-music-linux#74]
Привет!

Обновился до 5,0,21 (yandex-music_5.0.21_amd64.deb) Ubuntu 22.04.4 LTS Wayland. Пропал значок в трее и при нажатии на `x` теперь приложение закрывается, раньше сворачивалось

В остальном - круть

**Comment by cucumber-sp** [comment]
Привет. Теперь трей нужно дополнительно включить в конфиге 
https://github.com/cucumber-sp/yandex-music-linux?tab=readme-ov-file#tray-mode

**Comment by pashtet422** [comment]
Не работает. На эту настройку в конфиге реакции ноль. Fedora 40, Gnome 46, Wayland

**Comment by mishich666** [comment]
@pashtet422 
Я сделал так (и сохранил себе в заметках):
Начиная с версии 5.0.21 для того, чтобы появлялся значок в трее и приложение не завершалось при нажатии `x` необходимо добавить
```
TRAY_ENABLED=1
```
в файл настроек `$HOME/.config/yandex-music.conf`
(https://github.com/cucumber-sp/yandex-music-linux?tab=readme-ov-file#tray-mode).

После перезапустить приложение.

**Comment by pashtet422** [comment]
@mishich666

Спасибо за ответ, но вышеперечисленные действия не приводят к результату в моем случае. Версия приложения 5.1.4

**Comment by cucumber-sp** [comment]
> @mishich666
> 
> Спасибо за ответ, но вышеперечисленные действия не приводят к результату в моем случае. Версия приложения 5.1.4
> 
> UPD. При закрытии приложения по кнопке X. окно закрывается, но музыка продолжает играть, Но иконки в трее по прежнему нет. У других приложений (кроме Telegram desktop) иконка в трее появляется. Пропали они вроде бы после обновления федоры

если продолжает играть значит tray режим включен. скорее всего это бага вашего окружения

**Comment by thodt** [comment]
В 5.31.2 опять пропал значок в трее, в yandex-music.conf 
```
ELECTRON_CUSTOM_BIN=
ELECTRON_ARGS="--no-sandbox"
TRAY_ENABLED=1
```
Но значка нет.

**Comment by cucumber-sp** [comment]
> В 5.31.2 опять пропал значок в трее, в yandex-music.conf 
> 
> ```
> 
> ELECTRON_CUSTOM_BIN=
> 
> ELECTRON_ARGS="--no-sandbox"
> 
> TRAY_ENABLED=1
> 
> ```
> 
> Но значка нет. При нажатии кнопки закрытия приложение закрывается и воспроизведение останавливается.
> 
> ОС KDE Neon 6.2

В данный момент кодовая база сильно перерабатывается Яндексом, видимо для того чтобы официально поддержку линьки завезти. Из-за этого трей убран временно.
