### ISSUE TITLE
App is not restarting

### ISSUE THREAD

**Issue by XeemPad** [cucumber-sp/yandex-music-linux#76]
В последней версии с AUR (5.1.2-1), если закрыть приложение, а после этого попытаться открыть его снова, то ничего не получится. Проблема решается убийством процесса Electron - после этого Я.Музыка без проблем запускается. Если есть возможность пофиксить это, было бы хорошо.
-----------------------------------------------------
On the last version from AUR (5.1.2-1), if you close the app and then try to open it again, it fails to. It is solved by killing an Electron proccess - Music app launches normally then. Would be great if you could fix it.

**Comment by cucumber-sp** [comment]
> ## В последней версии с AUR (5.1.2-1), если закрыть приложение, а после этого попытаться открыть его снова, то ничего не получится. Проблема решается убийством процесса Electron - после этого Я.Музыка без проблем запускается. Если есть возможность пофиксить это, было бы хорошо.
> On the last version from AUR (5.1.2-1), if you close the app and then try to open it again, it fails to. It is solved by killing an Electron proccess - Music app launches normally then. Would be great if you could fix it.

У вас включен трей? можете запустить из консоли и вывести лог при закрытии. При выключенном трее должно убиваться приложение при закрытии.

**Comment by cucumber-sp** [comment]
Пожалуйста, предоставьте больше информации
