### ISSUE TITLE
Пропал значёк в appindicator

### ISSUE THREAD

**Issue by mopo3ilo** [cucumber-sp/yandex-music-linux#77]
После последнего обновления (5.1.2) перестал выводиться значёк в appindicator (трэй).

aur/yandex-music 5.1.2-1
Arch Linux 6.6.29-1-lts
Gnome Shell 46

**Comment by cucumber-sp** [comment]
Привет. Решение здесь https://github.com/cucumber-sp/yandex-music-linux/issues/74
