### ISSUE TITLE
Открытие ссылок сразу в приложении

### ISSUE THREAD

**Issue by BartolomeyKant** [cucumber-sp/yandex-music-linux#80]
Не работает открытие ссылок сразу в приложении. Не понимаю это недоработка яндекса или приложение должно уметь как-то регистрироваться.

У меня браузер chromium

делимся ссылкой композиции [пример](https://music.yandex.ru/album/8721411/track/57825529?utm_source=desktop&utm_medium=copy_link)
пытаемся на нее перейти. Хочется, чтобы открылось приложение, либо случился запрос, где эту ссылку открыть.

**Comment by cucumber-sp** [comment]
Единственное что возможно добавить это ссылки типа yandexmusic://... но они не открываются с помощью той же композиции. Может уже дело в яндексе который сам должен дергать deeplink

**Comment by ein-shved** [comment]
@cucumber-sp возникла мысль добавить в форму багрепорта просьбу проверки поведения приложения на винде.

**Comment by BadWolf1st** [comment]
У меня на Windows 11 не открывается по ссылкам...

**Comment by BartolomeyKant** [comment]
> У меня на Windows 11 не открывается по ссылкам...

поинтересовался у коллеги. У него на windows 11 открывается в приложении, ну как минимум из телеграма

**Comment by ein-shved** [comment]
@BartolomeyKant у него точно бетка?
