### ISSUE TITLE
Можно сминить версию электрона на 30?

### ISSUE THREAD

**Issue by BadWolf1st** [cucumber-sp/yandex-music-linux#81]
У меня AUR просто пишет, мол 29 устарела.  Это конечно не критично, но хотелось бы.
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/115115085/ec0296ef-48c7-4e92-b669-68c6aadfcbfd)

**Comment by cucumber-sp** [comment]
> У меня AUR просто пишет, мол 29 устарела. Это конечно не критично, но хотелось бы. ![image](https://private-user-images.githubusercontent.com/115115085/333150251-ec0296ef-48c7-4e92-b669-68c6aadfcbfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjEzNjAsIm5iZiI6MTcxNjQ2MTA2MCwicGF0aCI6Ii8xMTUxMTUwODUvMzMzMTUwMjUxLWVjMDI5NmVmLTQ4YzctNGU5Mi1iNjY5LTY4YzZhYWRmY2JmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxMDQ0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmViMzkyNmYzNGQ5YjYyODc2YTJlMDQ3Njk2OGQwNmNmM2I4MWY5Yzg3ZWJmZWEzNGQ1Y2EwZTgxMmJhOTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VVynobTd8n4LZJU2i2dxWg6C4yD8bxOdSN539Nfzn8s)

вместо electron29-bin можно установить electron29. 30 версия нестабильна, буквально если окно перевести в полноэкранный режим то в любом приложении крашится.
