### ISSUE TITLE
Скоро здесь будет громко

### ISSUE THREAD

**Issue by Nab0y** [cucumber-sp/yandex-music-linux#84]
Вчера вечером приложение переключилось вот в такой режим переустановка мало помогает, подскажите может где чего нужно очистить
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/13904687/d5f44b83-4c1d-4ef9-8095-01af8c74480f)

**Comment by Nab0y** [comment]
Удаление папки ~/.config/YandexMusic после деинсталла не помогает, потом требует авторизации и результат все тот же что на скрине выше.

**Comment by ein-shved** [comment]
Хм. Аналогичная проблема

**Comment by Nab0y** [comment]
Пока поставил виндовую версию через wine, вроде работает. 
Вот такой временный workaround.

**Comment by Crazy-kun** [comment]
Подтверждаю.

**Comment by andreyalekseenko** [comment]
+

**Comment by thodt** [comment]
Аналогичная проблема с самого утра. Вчера всё работало отлично.
Переустановка с удалением ~/.config/YandexMusic не помогает, после авторизации тоже самое.

**Comment by ein-shved** [comment]
Есть у кого-нибудь на винде проверить - работает ли бетка?

**Comment by mishich666** [comment]
> Есть у кого-нибудь на винде проверить - работает ли бетка?

На маке у товарища работает

**Comment by raydevilevil** [comment]
Видел, что вышла бета 5.6.0 под винду, интересно, как быстро обновится тут..

**Comment by ein-shved** [comment]
кажется, `5.6.0` поменял раскладку пакета и API. Теперь ломатся сборка пакета, а старые версии - не работают с сервером.

**Comment by sala2000** [comment]
![Screenshot 2024-07-03 175744](https://github.com/cucumber-sp/yandex-music-linux/assets/31439828/46f7e4a4-e1ef-4678-83bb-f59fcda1661e)
на винде на версии 5.5.0 работает

**Comment by ArtMin96** [comment]
Та же проблема существует и в Ubuntu 24.04 LTS

**Comment by ZeuSJke** [comment]
Та же проблема на Arch

**Comment by pashtet422** [comment]
+1. Fedora 40

**Comment by cucumber-sp** [comment]
Потратил пару часов но не нашел как это отключить пока. Весь код через  Webpack прогнали, в нем еще и разобраться нереально

**Comment by raydevilevil** [comment]
> Потратил пару часов но не нашел как это отключить пока. Весь код через Webpack прогнали, в нем еще и разобраться нереально

Надежда на решение имеется или стоит сесть на вино?

**Comment by ein-shved** [comment]
@cucumber-sp А ты запускал 5.6.0?

**Comment by DyukDavis** [comment]
Сегодня перепробовал варианты с откатом на более поздние версии до 5.4.2, чистил кэш, пробовал ставить из разных источников, обновил электрон. Ситуация без изменений.

**Comment by thodt** [comment]
Поставил последнюю 5.6, ничего не изменилось. ОС KDE Neon.

**Comment by sorokinkir** [comment]
Linux mint, версия пакета 5.6.0 без изменений.

**Comment by prostopasta** [comment]
пока не починили я пользуюсь Cassette - https://flathub.org/apps/io.github.Rirusha.Cassette

**Comment by Ravshanovich** [comment]
Тоже  Simply Linux 10.2   версия 5.6.0

**Comment by Ravshanovich** [comment]
![yaya](https://github.com/cucumber-sp/yandex-music-linux/assets/43450281/5dd28f45-0cee-4098-95f7-5942d99a971e)

**Comment by BungaaFACE** [comment]
@cucumber-sp может быть есть какой-то режим разработчика, чтобы посмотреть api-запросы к бэку? думаю проблема кроется там (какой-нибудь header не добавляется или неверный формат запроса. Ну или в header добавляется system: Linux, а бэк видит незнакомую систему и реджектит)

**Comment by BungaaFACE** [comment]
Можете кто-нибудь собрать AppImage c enableDevTools: true ? Я не разбираюсь в сборке приложений и запуске исходников, но могу попробовать посмотреть, что там в самом приложении происходит. 

Настройка находится в tar/yandex-music_5.6.0_x64/usr/lib/yandex-music/yandex-music.asar   , дальше по пути со скриншота
![image](https://github.com/cucumber-sp/yandex-music-linux/assets/117712541/ac3b3511-eeb3-401a-82cf-f52b82447474)

**Comment by 0x0000ABBA** [comment]
Подтверждаю, та же проблема

**Comment by asaldele1** [comment]
Я смог починить! Сейчас сделаю пулл реквест

**Comment by asaldele1** [comment]
Мой патч будет менять js chunk. Является ли проблемой полная запись огромной строки в файле патча (чанк может поменяться)?

**Comment by asaldele1** [comment]
https://github.com/cucumber-sp/yandex-music-linux/pull/88

Скачать рабочую версию до мёржа можно здесь: https://github.com/asaldele1/yandex-music-linux/actions/runs/9811612233

**Comment by Nab0y** [comment]
@asaldele1 @cucumber-sp Ребята, вы лучшие! Все работает, спасибо!

**Comment by 0x0000ABBA** [comment]
@asaldele1 @cucumber-sp спасибо вам большое <3

**Comment by barri3303** [comment]
@asaldele1 а можете подсказать как установить это приложение по ссылке на арч линукс?

**Comment by asaldele1** [comment]
@barri3303 исправленная версия уже находится в основном репозитории

**Comment by barri3303** [comment]
> @barri3303 исправленная версия уже находится в основном репозитории
простите я не совсем опытный. это где? на aur?

**Comment by barri3303** [comment]
@asaldele1 а всё, спасибо)

**Comment by Crazy-kun** [comment]
Большое спасибо, чуваки. Теперь снова можно жить.

**Comment by Dodje** [comment]
Ура, спасибо!

**Comment by BartolomeyKant** [comment]
А в AUR новый релиз апстрима ждать или патч туда раньше попадет?

**Comment by BartolomeyKant** [comment]
> А в AUR новый релиз апстрима ждать или патч туда раньше попадет?

А понял нужно было с cleanBuild собирать
