### ISSUE TITLE
Приложение отрисовывает с блюром

### ISSUE THREAD

**Issue by 555f** [cucumber-sp/yandex-music-linux#85]
![Снимок экрана от 2024-07-03 10-48-45](https://github.com/cucumber-sp/yandex-music-linux/assets/72383603/219fc4c3-8800-418e-8777-3a898cdcf760)

 Arch Linux, wayland

**Comment by utlark** [comment]
OS: Fedora Linux 40 (Workstation Edition) x86_64
Display (U28G2XU2): 3840x2160 @ 60 Hz (as 1920x1080) in 28″ [External]
DE: GNOME 46.4
WM: Mutter (Wayland)

Помогло удаление "--ozone-platform=wayland" из yandex-music.sh

**Comment by cucumber-sp** [comment]
Fixed in https://github.com/cucumber-sp/yandex-music-linux/commit/cd5f79e0e175961966062379cd80c869631dde99
