### ISSUE TITLE
Window frame visual bug

### ISSUE THREAD

**Issue by lisia2k** [cucumber-sp/yandex-music-linux#89]
Привет, при разворачивании на весь экран появляется визуальный баг, фрейм окна становится прозрачным, начинает дергаться и "плыть"(
![image](https://github.com/user-attachments/assets/b660df80-a341-428d-b1b6-6f8faf3548cb)

**Comment by cucumber-sp** [comment]
Possibly duplicate  #85

**Comment by cucumber-sp** [comment]
Протестируйте на последней версии
