### ISSUE TITLE
Ошибка при попытке зайти в приложение под аккаунтом Яндекса

### ISSUE THREAD

**Issue by eaStepanov** [cucumber-sp/yandex-music-linux#93]
Добрый день! Установил yandex-music-5.8.2-1.x86_64.rpm на Rosa Linux 12.5.1 (ниже параметры системы) через стандартный менеджер пакетов. Приложение нормально запустилось и предложило войти под учеткой Яндекса. Я указал данные, учетка отобразилась, но при нажатии на неё внутри приложения выходит ошибка "что-то пошло не так" и предложение перезагрузить приложение. Перезагрузка не помогает. Ранее ставил win приложение через PortProton и оно нормально работало.

OS: ROSA Fresh Desktop 12.5.1, platform 2021.1 x86_64 
Kernel: 6.6.27-generic-3rosa2021.1-x86_64 
Uptime: 23 hours, 26 mins 
Packages: 3556 (rpm), 12 (flatpak) 
Shell: bash 5.1.16 
Resolution: 1920x1080 
DE: Plasma 5.27.10

**Comment by cucumber-sp** [comment]
Ошибки при запуске через терминал? Или в консоле с включенными Dev Tools?

**Comment by eaStepanov** [comment]
> Ошибки при запуске через терминал? Или в консоле с включенными Dev Tools?

Просто через GUI по ярлыку из меню запуска. Но странность в том, что сейчас проверил и логин прошел нормально.) Вопрос снят.
