### ISSUE TITLE
Failed to connect to apt.cucumber-space.online

### ISSUE THREAD

**Issue by VVhiteCoder** [cucumber-sp/yandex-music-linux#94]
```
$ curl -fsSL https://apt.cucumber-space.online/key.gpg
curl: (7) Failed to connect to apt.cucumber-space.online port 443 after 90 ms: Couldn't connect to server

```
Looks like something is wrong with the repo server. I'm trying to install the last version because the version 5.0.19 is showing only this screen:
![image](https://github.com/user-attachments/assets/e64a49cd-31c0-4c59-897a-23ee7cc56c23)

_Ubuntu 22.04.4 LTS_

**Comment by cucumber-sp** [comment]
Fixed

**Comment by deepcitizen** [comment]
Это снова произошло
