### ISSUE TITLE
Текстомузыка 

### ISSUE THREAD

**Issue by BartolomeyKant** [cucumber-sp/yandex-music-linux#95]
В новой версии 5.8.2 говорят появилась текстомузыка. https://github.com/cucumber-sp/yandex-music-linux/releases/tag/v5.8.2

> Открывайте Текстомузыку из обычного плеера, а из большого плеера — через контекстное меню трека. Текст будет прокручиваться на экране по ходу песни

Впервые узнал, что есть еще большой плеер.

Но у меня никакой текст не появляется и ничего не прокручивается.

У всех так?

**Comment by BartolomeyKant** [comment]
В мобильном приложении текст у этой песни есть https://music.yandex.ru/album/3542/track/43117?utm_source=desktop&utm_medium=copy_link

**Comment by VodoGamer** [comment]
+ на 5.8.3, Текстомузыка не работает корректно

**Comment by ProggerX** [comment]
+, не работает
может конечно надо писать яндексу, но...

**Comment by Zink321** [comment]
На винде текстомузыка работает нормально, тут она почему то переключает сразу на обложку трека

**Comment by cucumber-sp** [comment]
![image](https://github.com/user-attachments/assets/522a7217-ffb5-4afb-98a3-062b00a84cf9)
![image](https://github.com/user-attachments/assets/91d48817-4a64-46c0-b473-887b4859a7da)
видимо теперь нужно учиться вытягивать ключ из приложения вместо его подмены на фейковый как это делается сейчас

**Comment by Zink321** [comment]
> ![image](https://private-user-images.githubusercontent.com/100789522/354929309-522a7217-ffb5-4afb-98a3-062b00a84cf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDk2NTQsIm5iZiI6MTcyMjg0OTM1NCwicGF0aCI6Ii8xMDA3ODk1MjIvMzU0OTI5MzA5LTUyMmE3MjE3LWZmYjUtNGFmYi05OGEzLTA2MmIwMGE4NGNmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQwOTE1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDg5ZjlkN2ZhMzI1ZDMyOGFlODdhZDRiZWFhMzljMjI5ZWZiOTg5M2YzMzIwYzQyMWYyYzYzMmUwMTY3YzFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hm_LI69rSgyWSjdeNcMKMzLU7OXkvuINtPCAEwRw1Dk) ![image](https://private-user-images.githubusercontent.com/100789522/354929319-91d48817-4a64-46c0-b473-887b4859a7da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDk2NTQsIm5iZiI6MTcyMjg0OTM1NCwicGF0aCI6Ii8xMDA3ODk1MjIvMzU0OTI5MzE5LTkxZDQ4ODE3LTRhNjQtNDZjMC1iNDczLTg4N2I0ODU5YTdkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQwOTE1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjM0ZTk5NWM4MzY0YzNmMzA4OWE0MTFmZGMwOTBiYzQ4NzFjMTIyNjQ3OWQ1MjY4MTE1MmMxZTdiNTBmMjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MYEBk_-me6Qxqa48a-NkAeNWAJyAryA4IE3r8UpEuU4) видимо теперь нужно учиться вытягивать ключ из приложения вместо его подмены на фейковый как это делается сейчас

кстати, у яндекса нет вопросов к этому проекту? Просто может они даже могли бы помочь

**Comment by cucumber-sp** [comment]
> кстати, у яндекса нет вопросов к этому проекту? Просто может они даже могли бы помочь

Пока ничего не видел, но я не думаю что это будет интересно, тем более через всякую поддержку к команде разработки не пробиться

**Comment by Nab0y** [comment]
> ![image](https://private-user-images.githubusercontent.com/100789522/354929309-522a7217-ffb5-4afb-98a3-062b00a84cf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDU3MzIsIm5iZiI6MTcyMzQ0NTQzMiwicGF0aCI6Ii8xMDA3ODk1MjIvMzU0OTI5MzA5LTUyMmE3MjE3LWZmYjUtNGFmYi05OGEzLTA2MmIwMGE4NGNmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwNjUwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTJlNzYwZTAyYjVkY2Y2N2E4ODdkMjhjZjgzNThiZmMyNjA5MGNhYTRkNzFiYWNhMGNhMWIxMTljNDJmZDhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KD08s38AWCcTFrmE_IWsKuR3o8qsSduwuWIe-qSq-cI) ![image](https://private-user-images.githubusercontent.com/100789522/354929319-91d48817-4a64-46c0-b473-887b4859a7da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDU3MzIsIm5iZiI6MTcyMzQ0NTQzMiwicGF0aCI6Ii8xMDA3ODk1MjIvMzU0OTI5MzE5LTkxZDQ4ODE3LTRhNjQtNDZjMC1iNDczLTg4N2I0ODU5YTdkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwNjUwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjEzMmU0MGI1ODY1MDRhZWFmYTkzMTZiZjRlZWQ5Mzc1OTI2YWZhYjdmOTRiZjY0OGVjNDJmMjA0ZTQwOTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DqQvWWrebZgPbbUonQozL9pvzNEa_wM4bWuKWoat2_8) видимо теперь нужно учиться вытягивать ключ из приложения вместо его подмены на фейковый как это делается сейчас

Код вот этого проекта https://github.com/llistochek/yandex-music-downloader/blob/main/ymd/ym_api/api.py не поможет в решении данного вопроса и https://github.com/cucumber-sp/yandex-music-linux/issues/96 ведь он так же ходит к api и генерирует подпись, правда из ключа сессии куки, но наверное его можно получить автоматически

**Comment by cucumber-sp** [comment]
Fixed #98

**Comment by Spp595** [comment]
Версия 5.31.2
Arch Aur версия
обновился и теперь текст не открывается
