### ISSUE TITLE
Кнопки управления окном слева

### ISSUE THREAD

**Issue by jkreet** [cucumber-sp/yandex-music-linux#97]
5.10.2

![image](https://github.com/user-attachments/assets/ad77c160-4792-40e0-9056-c0a4f2988811)

Во всех остальных окнах справа.

Ubuntu 24.04 LTS
Gnome 46
Wayland

**Comment by akaLoki-d** [comment]
Была такая же фигня. в процессе экскриментов - поставил КДЕ - кнопки перехали на право. так - мысли вслух...

**Comment by cucumber-sp** [comment]
Replaced with built-in custom titlebar https://github.com/cucumber-sp/yandex-music-linux/commit/88a798d2c217f434f9f1f58be48d81af3eafdedc

**Comment by AndyDroid10X** [comment]
> Replaced with built-in custom titlebar [88a798d](https://github.com/cucumber-sp/yandex-music-linux/commit/88a798d2c217f434f9f1f58be48d81af3eafdedc)

Now the window looks weird, without any rounded corners
![image](https://github.com/user-attachments/assets/ae190329-fb70-4216-8132-af4ec426eb24)
